[package]
name = "codegen"
version = "0.0.1"
license = "MIT/Apache-2.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1"
fn-error-context = "0.2"
heck = "0.5"
nom = "8"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
xmltree = "0.11"
